fail gracefully during cleanup

diff --git a/.github/workflows/create-test-wf.yml b/.github/workflows/create-test-wf.yml
--- a/.github/workflows/create-test-wf.yml
+++ b/.github/workflows/create-test-wf.yml
@@ -57,5 +57,6 @@ jobs:
           path: log.txt
 
       - name: Cleanup work directory
-        run: rm -rf work
+        # cleanup and fail gracefully if I get a permission error
+        run: rm -rf work || true
         if: always()
